/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package real.health;

import real.health.Patient.*;
import real.health.PatientLogin.*;
import real.health.SQL.HealthConn;
import real.health.GUI.*;
import java.sql.*;
import java.sql.ResultSet;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.UUID;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;

public class App extends JFrame {
    public App() {
        // Create a new instance of the welcomeScreen class
        welcomeScreen screen = new welcomeScreen();

        // Make the welcome screen visible
        screen.setVisible(true);
    }

    // TODO: Fix window popping up in upper left corner, replace current window
    // instead

    public static void main(String[] args) {
        SwingUtilities.invokeLater(App::new);
    }
}
